services:
  metabase:
    image: metabase/metabase
    container_name: c9cf13c6d71180894342a6e4eaace3a8922f45c6b7c9f659d5f3cddbf2e8f062
    ports:
      - "3000:3000"
    volumes:
      - ./metabase-data:/metabase-data
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
